### ISSUE TITLE
image principale sur la page projet

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#10]
devrait être automatiquement vertical

**Comment by npeltier** [comment]
je ne comprends pas @misterwhitedesign ?

**Comment by misterwhitedesign** [comment]
Ben tu vois l'image est pivotée, verticalement sur la maquette, j'aimerais que quand on choisi l'image principale (une image horizonatle) il la fasse picoter. Qu'on ne soit pas obligé de créer une image verticale specifique.
Merci !

**Comment by npeltier** [comment]
apparement tu peux la faire pivoter dans l'édition de l'image elle même, ça suffit non? ou tu veux un truc automatique?

**Comment by npeltier** [comment]
par exemple : http://dev.potager-liberte.com/projets/gymnase-liberte/ bon le problème c'est que c'est la même image que celle utilisée dans la gallerie, il faudrait l'ajouter 2 fois...ça permettrait aussi de reduire la taille de certaines images
