### ISSUE TITLE
visionneuse image sur la page projet

### ISSUE THREAD

**Issue by npeltier** [misterwhitedesign/potager#17]

**Comment by misterwhitedesign** [comment]
c'est vraiment le merdier cette page, mais la lightbox me plait
http://dev.misterwhite.org/page-1/

celui là j'aime bien aussi
https://kellenrenstrom.com

**Comment by npeltier** [comment]
@misterwhitedesign bon j'ai trafiqué un truc, tu me dis. Faudrait des icones gauche et droite, ou des images en hover, si tu veux
