### ISSUE TITLE
editeur de styles pour les page standard

### ISSUE THREAD

**Issue by npeltier** [misterwhitedesign/potager#27]

**Comment by npeltier** [comment]
ouf!

**Comment by npeltier** [comment]
modification gutenberg: tu ajoutes un paragraphe, puis en cliquant dessus, tu as potager-1,2 ou 3
les styles ne correspondent pas vraiment dans l'éditeur, et le soulignage merite d'être ajusté, mais j'imagine que c'est moins urgent

**Comment by misterwhitedesign** [comment]
YO, oui mais je ne comprends pas comment modifier un projet avec gutemberg. c'est l'interface classique.

**Comment by misterwhitedesign** [comment]
Et serait il possible d'appliquer le style uniquement à un mot et pas à tous un paragraphe ?

**Comment by misterwhitedesign** [comment]
Ah ouai je relis le titre de l'issue et je comprends.
