### ISSUE TITLE
pages fixes - le bloc de texte devrait faire la même largeur que les blocs de texte "page projet" - 400 px si je ne m'abuse

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#45]

**Comment by npeltier** [comment]
c'est bon, ça non?

**Comment by misterwhitedesign** [comment]
yep
 !


…….………………….……………………….………………………………………………………………………………………
Stéphane Blanc

Le 8 mars 2019 à 18:47, Nicolas Peltier <notifications@github.com> a écrit :

c'est bon, ça non?
