### ISSUE TITLE
editeur de styles pour les page projet

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#46]
- Sur les pages projet je n’ai pas l’éditeur gutenberg, et je ne retrouve donc pas les style que tu as créer.

- Il faudrait pouvoir appliquer le style uniquement à un mot et pas à tous un paragraphe.

**Comment by npeltier** [comment]
tu ne peux pas passer en mode gutenberg? C'est systématiquement du inline et pas du block?

**Comment by misterwhitedesign** [comment]
ben je sais pas je comprend pas pourquoi c'est pas comme sur les pages, et je ne vois aucun endroit où passer en mode gutenberg

**Comment by npeltier** [comment]
<img width="437" alt="screenshot 2019-03-07 at 21 30 53" src="https://user-images.githubusercontent.com/1032754/53987115-5ad24780-4120-11e9-83cb-ce6e7efac304.png">
http://dev.potager-liberte.com/contact/

**Comment by misterwhitedesign** [comment]
Génial bravo !!!!

ya plus qu’à pouvoir faire la même chose dans les projets.


tellement sexy le fond dégradé dans le back office…

Merci.


…….………………….……………………….………………………………………………………………………………………
Stéphane Blanc

Le 7 mars 2019 à 21:32, Nicolas Peltier <notifications@github.com> a écrit :

Closed #46 <https://github.com/misterwhitedesign/potager/issues/46> via b02af84 <https://github.com/misterwhitedesign/potager/commit/b02af844ade16a31557990c01cb1419e3a24f945>.
