### ISSUE TITLE
cosmétique de la lightbox

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#48]

**Comment by npeltier** [comment]
?

**Comment by misterwhitedesign** [comment]
oui désolé, 
- enlever le cadre blanc
- remplacer la flèche/curseur par les flèches jointes (elles sont grosses oui)
- remplacer la croix par celle jointe

Merci.


[Archive.zip](https://github.com/misterwhitedesign/potager/files/3038056/Archive.zip)

**Comment by misterwhitedesign** [comment]
Alors bravo c'est très bien. 3 remarques : 👍 
- en fait les flèches, je voudrais que le curseur se transforme en flèche, comme c'était le cas à l'origine, mais avec MA flèche
- ensuite il y a un fond blanc transparent qui apparait en rollover sur partie droite ou gauche, je l'avais vu dans le css mais je te laisse le changer c'est plus sûr
- enfin les images verticales dépassent totalement

voilà.

**Comment by misterwhitedesign** [comment]
nouvelles images pour la nav. elle ont jamais fait + de 128 px. la croix est plus grosse.
On les voit pas mais y a des images (blanches)
![fermer](https://user-images.githubusercontent.com/44583601/56042895-5828ca80-5d3c-11e9-9fe7-e0d53a5a6229.png)
![fleche-droite](https://user-images.githubusercontent.com/44583601/56042897-58c16100-5d3c-11e9-8846-fd4a4e9b1c39.png)
![fleche-gauche](https://user-images.githubusercontent.com/44583601/56042898-58c16100-5d3c-11e9-8c7e-c2df09ed43a6.png)

**Comment by npeltier** [comment]
nouvelles images?

**Comment by misterwhitedesign** [comment]
ben elles sont là en fait. tu les vois pas mais si tu kick elle s'ouvre

**Comment by misterwhitedesign** [comment]
http://lyl.live/

**Comment by misterwhitedesign** [comment]
super ! subsiste un petit soucis sur les images verticales http://dev.potager-liberte.com/projets/un-lieu-pour-respirer/
Voir la très longue image bleu
