### ISSUE TITLE
pages fixes - ajouter la possibilité d'ajouter des images dans la colonne de gauche

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#59]

**Comment by npeltier** [comment]
? je ne suis pas sûr de comprendre @misterwhitedesign il y en a déjà, non? tu veux parler pour après la première page?

**Comment by npeltier** [comment]
check http://dev.potager-liberte.com/participez/

**Comment by npeltier** [comment]
et check http://dev.potager-liberte.com/prestations/ :-/
