### ISSUE TITLE
Possibilité de modifier le style des séparateurs wordpress et boutons

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#60]

**Comment by npeltier** [comment]
tu as un exemple de bouton?

**Comment by misterwhitedesign** [comment]
ah ben caro l'a viré
je t'ai mis un bouton test en bas de cette page
mais le plus important c'est le séparateur
Et quand je dis possibilité de modifier, c'est juste dans le css hein, pas dans le back office
merci !

http://dev.potager-liberte.com/participez/
