### ISSUE TITLE
image principale projet - l'afficher à -90°

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#62]
Je me souviens que ça posait un problème, que j'avais dit tant pis je le ferais moi même. Mais c'est chiant, ça implique d'avoir 2 images etc… 
ça pose un problème ou c'est faisable ?

Merci !

**Comment by npeltier** [comment]
@misterwhitedesign c'est complétement faisable, mais le faire "systématiquement" va être problématique, non?

**Comment by misterwhitedesign** [comment]
Tu as raison.
