### ISSUE TITLE
Affichage du texte de la home sur mobile - voir PJ police judiciaire

### ISSUE THREAD

**Issue by misterwhitedesign** [misterwhitedesign/potager#64]
![Screenshot_20190610-144821](https://user-images.githubusercontent.com/44583601/59196759-d0bad480-8b8f-11e9-9d66-e0fee3ee3c4e.jpg)

**Comment by npeltier** [comment]
donc, plus à gauche, le texte?

**Comment by misterwhitedesign** [comment]
plus a gauche effectivment, et peut etre la colonne de texte pus etroite.

**Comment by npeltier** [comment]
@misterwhitedesign figure toi que ça a du être corrigé ici: https://github.com/misterwhitedesign/potager/commit/068d322df02ecc59fefbce6244629e17271df022 mais le déploiement semble antérieur à ce commit
